### ISSUE TITLE
Question about the capacitor across the relay solenoid

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [Dfinitski/N7DDC-ATU-100-mini-and-extended-boards#14]
I'm curious why you have not used flyback protection diodes across the relays and have instead used a 1uF capacitor

Was this to fix some specific problem, e.g chattering  or perhaps noise spikes ?

**Comment by Dfinitski** [comment]
Because a powerful interference can be rectified on the diode and can turn on the relay. But maybe not.  Capacitors work well anyway. My oscilloscope show me very clean control lines.

**Comment by rogerclarkmelbourne** [comment]
OK. Thanks
