### ISSUE TITLE
Replacement Diodes

### ISSUE THREAD

**Issue by KevAmiga** [Dfinitski/N7DDC-ATU-100-mini-and-extended-boards#23]
Afternoon all - I need to replace 2 of the diodes on the underside of the board, but am unsure of the values, or in essence what diodes to purchase. Installing them shouldn't be a problem. This issue was down to my mistake, i needed to modify the case and slipped with the tool hitting the components (lesson learned!)

Please excuse the rubbish photo, it was the best i could get .

![image](https://user-images.githubusercontent.com/74002465/98255699-98324c80-1f75-11eb-9c9f-3ce014ef030c.png)

Their location on the board : 
![image](https://user-images.githubusercontent.com/74002465/98255857-cadc4500-1f75-11eb-837f-bc71430db728.png)

Hoping someone can point me in the right direction.

Many thanks

Kev

**Comment by Dfinitski** [comment]
Hi, Kevin
According to the schematic those are BAT41 diodes.
This info is not a secret, everyone can see the schematic.

**Comment by KevAmiga** [comment]
Excellent - thanks, have found the schematic will take a look.

Kev
