### ISSUE TITLE
v3.2 source code

### ISSUE THREAD

**Issue by rafael2k** [Dfinitski/N7DDC-ATU-100-mini-and-extended-boards#35]
Hi,
Here can I find the v3.2 PIC source code? Also, how to burn a now firmware to the pic?

**Comment by Dfinitski** [comment]
Hi.
I have uploaded V 3.2 sources.
Use a Pickit 3 programmer.

**Comment by rafael2k** [comment]
Thanks!!

**Comment by rafael2k** [comment]
I'll close the issue. I'm buying a Pickit 3 for me.

**Comment by rafael2k** [comment]
Also, sorry the late question - which software should I use to compile and flash the PIC?

**Comment by Dfinitski** [comment]
You don't need to compile the sources, the ready to flash hex files are here
 https://github.com/Dfinitski/N7DDC-ATU-100-mini-and-extended-boards/tree/master/ATU_100_EXT_board/FirmWare_PIC16F1938
But you can if you want, it is MikroC Pro for PIC.

Programmer's software is here https://drive.google.com/file/d/18wiH5RjL5R8ku7a9MQ4Hxx9SmUZInpvj/view?usp=sharing

**Comment by rafael2k** [comment]
I want to play with the firmware. Thanks a lot!
