### ISSUE TITLE
OLED Display inverted

### ISSUE THREAD

**Issue by PA3FUN** [Dfinitski/N7DDC-ATU-100-mini-and-extended-boards#48]
Hi David,
Help :).
I just updated the firmware of my ATU to v3.2 using the appropriate Github Hexfile to find out the OLED 128x64 display is now inverted. My question: would it be possible, using a hex-editor, to revert the display back to normal?
I checked out the source-code of "oled_control.c" and found line 186: Soft_I2C_Write (0xA6); // 0xA6 - normal, 0xA7 - inverse). Would this do the trick? And if so, would hex-editor suffice to change this single item?
What string would I than need to search for? I looked for A6 but got stranded..
Thanks for your help and for this inspiring project!
73's Christiaan Roselaar PA3FUN
![20210305_101628](https://user-images.githubusercontent.com/62031730/110094435-1d9b0180-7d9c-11eb-9aa5-5cb449c6ae62.jpg)

**Comment by Dfinitski** [comment]
Hi.
Read the manual. Cells 03 - 05.

**Comment by PA3FUN** [comment]
Hi Dave,
Thanks for your prompt reply!
Am I reading the wrong manual/version? (https://github.com/Dfinitski/N7DDC-ATU-100-mini-and-extended-boards/blob/master/ATU_100_EXT_board/ATU-100_Extended_Board_User_Manual_eng.pdf).
Cells 03-05 don't seem related to display-matters?

**Comment by PA3FUN** [comment]
Oops..
I accidentally closed this issue, my mistake, sorry.
Still looking forward to your reply to my previous post :)

**Comment by PA3FUN** [comment]
Ah. Values #03 and #05 in cell #01 are for inverted displays!
Dave,
All clear now.
And you were right; I should have read the manual better, it's in there all right.
Sorry to have wasted your time.
73's Christiaan PA3FUN

**Comment by grahamwhaley** [comment]
I've just had this same issue on an atu-100 I was donated and been fixing/updating to v3.2. By default my 128x64 display came out exactly like the original posting - inverted and with corruption on two edges.

I'll document the changes I made here for anybody else's future reference. The cells are documented in the pdf manual on github.

The first change is to set the display address and type in cells 00 and 01.

| Cell | Default | New Value | Notes |
| ---- | ----- | ----- | ---- |
| 00 | 4E | 78 | You may need value 7B, depending on your display |
| 01 | 01 | 05 | 05 is the inverted 128x64 value - (is listed in the pdf, but easy to miss) |

and then for the screen corruption we need to adjust cells 07 and 08 to fix the offsets:

| Cell | Default | New Value | Notes |
| ---- | ----- | ----- | ---- |
| 07 | 01 | 00 | No offset required for my display |
| 08 | 02 | 00 | No offset required for my display |

Here is hoping that helps somebody else find the information quicker in the future.
