### ISSUE TITLE
0 ohms between RF center pin and ground?

### ISSUE THREAD

**Issue by edwardstorlien** [Dfinitski/N7DDC-ATU-100-mini-and-extended-boards#55]
Hello, I am currently assembling the ATU-100 antenna tuner, but I noticed by coincidence something I think is wrong.

With a multimeter I noticed my ATU-100 board has approximately 0 ohms resistance between the RF center pin and ground. This is applies to both the RF input and RF output.

I can see on the schematic that the RF input's center pin is connected to ground through T1, but is it really 0 ohm resistance? Can anyone confirm that this is correct? I am unsure whether I have made a bad solder joint somewhere...

Thanks!

**Comment by Dfinitski** [comment]
Hi
Tandem match coiles are connected between center wire and ground for input
and output connector.

**Comment by edwardstorlien** [comment]
Hi again, thanks for answer.
Does that mean my multimeter will read 0 ohms, right? Nothing is wrong with my board?

**Comment by Dfinitski** [comment]
Yes, that is correct. There is a short by DC, and Hi Z by RF.

**Comment by MOUSE1025** [comment]
Dave,
You have the patience of a saint! Excellent support.
Kind regards,
Christopher Paul Ryan

**Comment by edwardstorlien** [comment]
Thank you so much for answer, Dave. Great support, I really appreciate it!
