### ISSUE TITLE
Capacitor Values for B1 B2

### ISSUE THREAD

**Issue by 2M0LWS** [Dfinitski/N7DDC-ATU-100-mini-and-extended-boards#6]
What are the values of the two smaller capacitors connected to the 0.1u capacitors in the attached image?

Any advice is greatly appreciated.

73s 2M0LWS

![Values](https://user-images.githubusercontent.com/64327110/80288071-4c345e80-872d-11ea-9550-883bac88a139.jpg)

**Comment by Dfinitski** [comment]
Hi
Those are 2 blocking 0.1uF capacitors for additional buttons.

сб, 25 апр. 2020 г. в 11:46, 2M0LWS <notifications@github.com>:

**Comment by 2M0LWS** [comment]
Many thanks for the quick reply. 73's, 2M0LWS
