### ISSUE TITLE
Beginners question: unsure about interpretation of schematic S7, S8 and S15

### ISSUE THREAD

**Issue by dl8bag** [Dfinitski/N7DDC-ATU-100-mini-and-extended-boards#63]
Hi,
I feel unsafe in how to interpret the pcb picture: Do I need to add wired bridges for S7, S8 and S15?
Vy 73 and a little sorry for asking 
Rolf

**Comment by Dfinitski** [comment]
Hi.
No any bridges there, that lines for understanding how relays work (
internal connections).

**Comment by dl8bag** [comment]
Hi,
thanks a lot for clarification and reassuring me. I couldn't find an differences between S7, S8, S15 and the other relays in the schematic - that's why I was asking.
Thanks again for the immediate reply and 73 de
Rolf
> Hi. No any bridges there, that lines for understanding how relays work ( internal connections).
...
