### ISSUE TITLE
Capacitor options

### ISSUE THREAD

**Issue by delight-f** [Dfinitski/N7DDC-ATU-100-mini-and-extended-boards#64]
Thanks @Dfinitski for such an amazing invention. I have bought a kit that has the bad brown ceramic SMD caps. 
I know silver mica caps are ideal, but is it possible to use say 1kV blue coated ceramic disc capacitor instead?

**Comment by Dfinitski** [comment]
Hi 
No, Those are very bad on high frequency ceramic capacitors. The best solution is ATC 800 or ATC 100 series.
