### ISSUE TITLE
Question about van 3.2

### ISSUE THREAD

**Issue by davidhay45** [Dfinitski/N7DDC-ATU-100-mini-and-extended-boards#87]
“Added new feature to disable all relays along with the timer display. New cell 35(33 for mini board) - 01 to activate the relay off function. Display Off Timer setup - cell 32 (30 for mini board). You can use this feature in your QRP setup where power consumption is critical.”

what is this to be used for?

**Comment by Dfinitski** [comment]
Hi. Bypass mode will be turned on when the display will be turned off.

**Comment by davidhay45** [comment]
So in other words when this is function activated by setting the EEPROM cell then putting the tuner into bypass mode the relays will be deactivated and the display will be turned off.

**Comment by Dfinitski** [comment]
No.
Display has a timer for turning it off after some period, an example 15 minutes.
Is this clear ?

**Comment by davidhay45** [comment]
OK, thnaks
