### ISSUE TITLE
Plans

### ISSUE THREAD

**Issue by davidhay45** [Dfinitski/N7DDC-ATU-100-mini-and-extended-boards#88]
Not an issue, just a statement.

I am planning to make my own version of the ATU-100 firmware.  This will be based on David N7DDC's 3.2 release and essentially will add the capability to command the tuner from an external device (probably a Raspberry PI using I2C) to cause the unit to set predetermined inductor and capacitor values on demand, a sort of manual mode.  This to enable the tuner to match at very low power for WSPR and FT8 etc where the transmit power levels needed for measuring the swr are simply too low.  In order to do this I will need to restructure the existing code to save programming space and so have the opportunity to make other mods.  For example, I may put the RF diode correction parameters into EEPROM to allow users to adjust the measured power to more accurate externally determined levels.

I am sharing this with this "forum" to see if there are other ideas.

Of course this is only possible because of David N7DDC's amazing generosity in sharing his designs, thank you David.  I have spent many years working as a software engineer and I know very well how difficult it is to make software for external release rather than for one's own use.

David M0TGC

**Comment by Dfinitski** [comment]
Hi
Yes, you are right, that is difficult to do what is other people want, not you :)
I am sure that the very low power transmitter must to work with very high efficient antennas and tuner don't need to use them.
