### ISSUE TITLE
Autotune wakes-up unexpectedly and triggers tuning sequence, even when SWR is very low, hence damaging relays at high power

### ISSUE THREAD

**Issue by satfan52** [Dfinitski/N7DDC-ATU-100-mini-and-extended-boards#95]
Hello, I use a 7X7 ATU-1000 tuner kit bought on Aliexpress based on the EU2AV design and that is supposedly designed to work up 1-1.2 KW.

The basic functionality works quite well and I was able to match at low (<100 W)  power level, semi-manually using the "Tune buton" ,  between 1.8 and 30 Mhz, an input SWR in the order of 3 to 6, down to 1.1-1.5 after matching
 
So the firmware works well for sure in semi manual mode using the "Tune button", but the tuner does not work well  in auto-tune mode with power levels in the order of 100W and more

There are two issues:

1) When the tune is good (SWR is low <= 1.5) auto-tune wake-up for unknown reasons  and starts a tuning sequence. This happens for power levels as from 100 W. This is a major issue when running at 1KW power levels because this unsolicited tuning sequence, at such high power level, inevitably damage or even breaks some relays. No so much an issue at 100W but a 1KW it damages some relays.

In practice,  I have to turn off auto-tune after the matching is done at low power otherwise auto-tune will wake-up even if the SWR is very low and the match perfect. Turning off auto-tune is required to avoid that uncontrolled wakes-up unexpectedly and kills/damages some relays when operating at high power levels. 

 The hardware settings is as follow : 100W = 1.2 V on FWD under a perfect 50 ohm load. Same for REF with the device reversed. There is no "overload" alarm on the display and the tuner matches well with  100W , no matching  issues at all. The coupler is a classical 20:1 tandem bridge, the "directivity" is better than 20dB in the range 1 - 30 Mhz. The two cRB2 and RB1  buttons are decoupled with 1nf capacitors and the Tuner button RB0 with a 100nf cap.  Disconnecting the 3 buttons completely from the PCB (to avoid picking up some rf  though the button wires) does not help at all. 

So what is going wrong ?  

2) The firmware says "ATU-100" on the screen, not "ATU-1000", it is the latest version. I don't think the aliexperess seller loaded the version of the firmware for high power. The SWR indication is good but the power level indicated is completely wrong, clearly over-estimated. Should I upload the version of the firmware with high power settings and a 20:1 ratio for the swr bridge ? Is this going to make a difference in the way autotune works, it it going to be more stable ? 

Thanks
Regards
Peter

**Comment by Dfinitski** [comment]
Hi. 1nf coupling may be not enough.  Try at least 100nf x 2.
When you increase a power , SWR could increase too and exceed the triggering level 0.3 by default.
You can make the trigger level higher or start the tuning process with higher level close to working level.
But first of all you should resolve the problem with wrong power measurement. Power and SWR should to be shown in 10% tolerance. 
Check what is tandem coefficient was set in this current firmware and correspond to real turn ratio. Check diodes on the tandem or swap them to known kind.

**Comment by satfan52** [comment]
Hello David, thanks for the reply.
The seller has now sent me the correct version of the hex file. After I loaded it in the PIC16F1938,  the problem is now  completely gone. Auto-tune is now stable at 1.2 kw  (about 3.28 V on FW after tuning the Potentiometer) on 14 Mhz and there is no more unexpected wake-up. The correct power is also indicated on the display. So the problem is solved as far as I am concerned. Regards. Peter
